[tool.poetry]
name = "one"
version = "0.1.0"
description = ""
authors = ["Benjamin Ye <benjamin.ye@georgian.io>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
jupyterlab = "^3.4.2"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
